#!/usr/bin/perl

use strict;
use warnings;

use IO::Select;
use Redis;

my $timeout = 0.1;

my $select = IO::Select->new();
$select->add(\*STDIN);

my $in  = Redis->new;
my $out = Redis->new;

my $channel = $ARGV[0] or die "Usage: pest <channel>\n";

$in->subscribe($channel, sub {
        my ($message, $topic, $subscribed_topic) = @_;
        print $message;
});

while (1) {
    if ($select->can_read($timeout)) {
        my $input = <STDIN>;
        if ($input) {
            $out->publish($channel, $input );
        } else {
            last;
        }
    }
    $in->wait_for_messages($timeout);
}
